### ISSUE TITLE
GeoPlot - Plotting mesh without vehicle properties

### ISSUE THREAD

**Issue by foxm1** [antarctica/GeoPlot#29]
Sometimes the mesh does not plot, but after adding vehicle information it does. Could be a problem with mesh construction, or a data problem. The Weddell Sea case below is an example.

[WeddellSea.zip](https://github.com/antarctica/GeoPlot/files/9861915/WeddellSea.zip)

**Comment by Ulvetanna** [comment]
I have had discussion with @SamuelHall700 and have moved this to a entourage issue

**Comment by SamuelHall700** [comment]
This issue is a part of the **GeoPlot** package, not within mesh construction. The issue occurs when a mesh has been constructed which contains a value of NaN against one or more of the properties of a `CellBox` (this happens very regularly in the mesh construction, such as when a `CellBox` in constructed over an area of land, the value for the SIC property of the `CellBox` will be `NaN`). **GeoPlot** currently does not know how to plot a value of `NaN` associated with a `CellBox`, so crashes when attempting to. 

This issue is not present after running vessel performance calculations on a mesh, due to the work-around that the vessel performance sets all `NaN` values present in a mesh to 0 (this is to be removed as part of the general re-architecture process [https://github.com/orgs/antarctica/projects/2/views/1?pane=issue&itemId=15344838](url)) 

**GeoPlot** should be extended to support plotting of cellboxes with `NaN` attributes (simply by not attempted to plot any attribute of a `CellBox` which is `NaN`)

**Comment by Ulvetanna** [comment]
As updates will be made in GeoPlot to include case dependent speeds and fuel usages I have assigned this task now to @gecoombs to address this small issue at the same time
